export const DISPLAY_FORMAT_TYPE = {
  NUMBER: 'NUMBER',
  DOLLAR: 'DOLLAR',
  PERCENT: 'PERCENT',
  DATE: 'DATE',
  TEXT: 'TEXT'
};

export const DISPLAY_NUMBER_FORMATS = {
  NONE: 'NONE',
  THOUSANDS: 'THOUSANDS',
  MILLIONS: 'MILLIONS',
  BILLIONS: 'BILLIONS'
};
